name: Basic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Hello World step
      run: echo "Hello, GitHub Actions!"

    - name: Display repository info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"

    - name: Test command splitting
      run: |
        echo "Some \
          string"
        echo "and another"
