name: Dependent

on:
  workflow_run:
    workflows: ["Basic"]
    types:
      - completed

jobs:
  event:
    runs-on: ubuntu-latest

    steps:
      - name: Display event info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.workflow_run.conclusion }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ toJson(github.event) }}"
